name: Publish container image GitHub Registry
on:
  release:
    types: [created]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set App Name
        run: 'echo "IMG_NAME=symphonyos/sympony-extension-knx:0.0.1-SNAPSHOT" >> $GITHUB_ENV'
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Pack Remote Build
        uses: dfreilich/pack-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          args: 'build ${{ env.IMG_NAME }} --builder paketobuildpacks/builder:full --env "BP_JVM_VERSION=17" --env "BP_MAVEN_SETTINGS_PATH=.github/workflows/settings.xml" --env "GITHUB_TOKEN=$GITHUB_TOKEN" --path . --publish'
